# /etc/crowdsec/profiles.yaml
- name: default_profile
  filters:
    - "true"
  decisions:
    - type: ban
      duration: 8h
  on_success: break

- name: repeat_offenders
  filters:
    - "Alert.Remediation == true && Alert.Source.IP in RecentSource(24h)"
  decisions:
    - type: ban
      duration: 48h
  on_success: break

- name: chronic
  filters:
    - "Alert.Source.IP in RecentSource(7d)"
  decisions:
    - type: ban
      duration: 30d
  on_success: break
