Protocol 2
TCPKeepAlive yes
AddressFamily inet
Port 22
AllowUsers ducky overseer
PubkeyAuthentication yes
AuthorizedKeysFile  .ssh/authorized_keys
AuthenticationMethods publickey
HostKey /etc/ssh/ssh_host_ed25519_key
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 2m
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PasswordAuthentication no
PermitUserEnvironment no
PermitEmptyPasswords no
AllowAgentForwarding no
AllowTcpForwarding no
PermitRootLogin no
X11Forwarding no
PermitTunnel no
GatewayPorts no
StrictModes yes
MaxAuthTries 3
MaxSessions 3
PrintMotd no
PidFile /var/run/sshd.pid
