error_log /tmp/error.log;
pid /tmp/nginx.pid;
events {}
stream {
    # Sven Co-Op Dedicated Server
    server {
        listen 27015 udp;
        proxy_pass 10.99.1.100:27015;
    }
    server {
        listen 27016 udp;
        proxy_pass 10.99.1.100:27016;
    }
}
http {
    # Rootless workaround
    proxy_temp_path /tmp/proxy_temp;
    client_body_temp_path /tmp/client_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;
    access_log  /tmp/access.log;
    # Serve proper mime to clients
    include mime.types;
    default_type application/octet-stream;
    # FastDL server setup
    sendfile on;
    server_tokens off;
    autoindex on;
    gzip on;
    map $http_user_agent $allowed_ua {
        default 0;
        "~*^Valve/Steam HTTP Client 1\.0.*" 1;
    }
    server {
        server {
        listen 8080;
        listen [::]:8080;
        server_name _;
        root /var/www/fastdl;
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime off;
        client_max_body_size 0;
        # Serve proper mime to clients
        include mime.types;
        default_type application/octet-stream;
        # FastDL server setup
        sendfile on;
        server_tokens off;
        autoindex on;
        gzip on;
        map $http_user_agent $allowed_ua {
            default 0;
            "~*^Valve/Steam HTTP Client 1\.0.*" 1;
        }
        location ~* \.(bak|txt|scr|log|inf|fgd|exe|dll|7z|app|appinstaller|application|appx|appxbundle|ps1|bat|sh|cmd|bgi|bin|btm|cab|chm|com|cpl|crx|diagcab|msi|hta|gadget|inf|jar|manifest|pdf|oxt|ppkg|reg|scf|settingcontent-ms|settingscontent-ms|swf|vbscript|vbs|vbe|vb) {
            deny all;
            return 403;
        }
        location ~* \.(addons|cl_dlls|classes|dlls|events|manual)/ {
            deny all;
            return 403;
        }
        location / {
            return 444;
        }
        location /svencoop_addon {
            if ($allowed_ua = 0) {
                return 403;
            }
            alias /var/www/fastdl/svencoop_addon/;
            add_header Cache-Control "public, max-age=31536000, immutable";
        }
    }
}
